### ISSUE TITLE
Error of using redis in python

### ISSUE THREAD

**Issue by kelvinlyy** [kelvinlyy/fyp21-22#8]
```
>>> import redis
>>> r = redis.StrictRedis(host='localhost', port=6379, db=0)
>>> r.set('foo', 'bar')
```
Traceback (most recent call last):
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/data/yylaiai/anaconda3/envs/py36/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

**Comment by kelvinlyy** [comment]
Solution:

1. comment out `bind 127.0.0.1` in redis.conf
2. Start a redis server on a terminal which is accessible by the python script
